---

- name: install fish by apt
  when: ansible_pkg_mgr == "apt"
  become: yes
  block:
  - name: add fish 2.* PPA
    apt_repository:
      repo: ppa:fish-shell/release-2

  - name: install fish by apt
    apt:
      name: fish
      update_cache: yes

- name: install fish
  become: yes
  package:
    name: fish

- name: copy config files
  synchronize:
    src: fish/
    dest: "{{ fish_config_dir }}/"

- name: install fisherman
  block:
    - name: create directory
      file:
        name: "{{ fish_config_dir }}/functions/"
        state: directory

    - name: install fisherman
      get_url:
        url: https://git.io/fisher
        dest: "{{ fish_config_dir }}/functions/fisher.fish"

- name: install fisherman packages by fishfile
  block:
    - name: set fishfile
      copy:
        src: fisherman/fishfile
        dest: "{{ fish_config_dir }}/"

    - name: install fisherman packages
      shell: fisher
      args:
        executable: /usr/bin/fish
      register: fisher
      changed_when: "'Installing' in fisher.stdout"

- name: enable triggered functions
  lineinfile:
    path: "{{ fish_config_dir }}/config.fish"
    line: ls_on_cd
