---

- name: install by apt
  when: ansible_pkg_mgr == "apt"
  apt:
    name: "{{ item.name }}"
  with_items:
    - name: clamav
    - name: clamav-daemon
    - name: clamdscan

- name: create scan log directory
  file:
    path: "{{ clamdscan_log_dir }}"
    state: directory
    owner: clamav
    group: adm
    mode: g+w

- name: create scan log file if missing
  copy:
    dest: "{{ clamdscan_log_dir }}/{{ clamdscan_log_filename }}"
    force: no
    content: ""
    owner: clamav
    group: adm
    mode: g+w

- name: add virus-scan command
  copy:
    src: clamdscan.sh
    dest: /usr/local/bin/virus-scan
    mode: a+x
