- name: setup `bash.d/` in bash profile
  blockinfile:
    dest: "{{ item }}"
    block: "{{ lookup('file', 'bash.d.sh') }}"
  with_items:
  - ~/.profile
  - ~/.bash_profile
  when: item|exists

- name: make `{{ bash_profile_dir }}/`
  file:
    path: "{{ bash_profile_dir }}"
    state: directory
