- name: setup `bash.d/` in bash profile
  blockinfile:
    dest: "{{ item }}"
    block: "{{ lookup('file', 'bash.d.sh') }}"
  with_first_found:
    - "{{ ansible_env.HOME }}/.bash_profile"
    - "{{ ansible_env.HOME }}/.bash_login"
    - "{{ ansible_env.HOME }}/.profile"

- name: make `{{ bash_profile_dir }}/`
  file:
    path: "{{ bash_profile_dir }}"
    state: directory
