- name: setup `bash.d/` in bash profile
  blockinfile:
    dest: "{{ item }}"
    block: "{{ lookup('file', 'bash.d.sh') }}"
  with_first_found:
    - ~/.bash_profile
    - ~/.bash_login
    - ~/.profile

- name: make `{{ bash_profile_dir }}/`
  file:
    path: "{{ bash_profile_dir }}"
    state: directory
