---
- hosts: localhost
  connection: local
  become: yes

  roles:
    - role: ubuntu
      when: ansible_distribution == "Ubuntu"
      tags:
        - system

    - role: ubuntu/ansible
      tags:
        - system

    - role: ubuntu/gnome
      become: no
      tags:
        - user

    - role: bash
      become: no
      tags:
        - user

    - role: go
      become: no
      tags:
        - user

    - role: anyenv
      become: no
      tags:
        - user
        - language
