# Ansible Galaxy Roles

- src: geerlingguy.ansible
  version: 2.0.2

- src: https://github.com/Wintus/ansible-role-bash-fragments
  name: wintus.bash-fragments

- src: https://github.com/Wintus/ansible-role-fish
  name: wintus.fish

- src: https://github.com/Wintus/ansible-role-git
  name: wintus.git

- src: https://github.com/Wintus/ansible-role-gnome
  name: wintus.gnome

- src: https://github.com/Wintus/ansible-role-oea
  name: wintus.oea

- src: https://github.com/Wintus/ansible-role-fcitx
  name: wintus.fcitx

- src: https://github.com/Wintus/ansible-role-anyenv
  name: wintus.anyenv

- src: https://github.com/Wintus/ansible-role-haskell-stack
  name: wintus.haskell-stack

- src: https://github.com/Wintus/ansible-role-go-tools
  name: wintus.go-tools

- src: https://github.com/Wintus/ansible-role-rust-tools
  name: wintus.rust-tools

- src: https://github.com/Wintus/ansible-role-spacemacs
  name: wintus.spacemacs

- src: https://github.com/Wintus/ansible-role-yarn
  name: wintus.yarn
