# Ansible Galaxy Roles

- src: geerlingguy.ansible
  version: 2.0.2

- src: https://github.com/Wintus/ansible-role-bash-fragments
  name: wintus.bash-fragments

- src: https://github.com/Wintus/ansible-role-git
  name: wintus.git

- src: https://github.com/Wintus/ansible-role-oea
  name: wintus.oea

- src: geerlingguy.nodejs
  version: 5.1.1

- src: https://github.com/Wintus/ansible-role-haskell-stack
  name: wintus.haskell-stack
