---
- hosts: local
  roles:
    - role: geerlingguy.ansible
      become: yes
      tags:
        - system

    - role: base
      tags:
        - system

    - role: oea
      become: yes
      tags:
        - system

    - role: gnome
      when: lookup('env','XDG_CURRENT_DESKTOP') | regex_search('GNOME')
      tags:
        - user
        - desktop

    - role: fcitx
      tags:
        - system

    - role: wintus.bash-fragments
      tags:
        - user

    - role: fish
      tags:
        - system
        - user

    - role: emacs
      tags:
        - user

    - role: wintus.git
      tags:
        - system
        - user

    - role: jetbrains
      tags:
        - system

    - role: go
      tags:
        - user

    - role: anyenv
      tags:
        - user
        - language

    - role: wintus.haskell-stack
      tags:
        - system
        - language

    - role: rust
      tags:
        - system
        - language

    - role: nodejs
      tags:
        - user
        - system
        - language
