---
- hosts: localhost
  connection: local

  roles:
    - role: ubuntu
      become: yes
      when: ansible_distribution == "Ubuntu"
      tags:
        - system

    - role: ansible/apt
      become: yes
      when: ansible_pkg_mgr == "apt"
      tags:
        - system

    - role: oea
      become: yes
      tags:
        - system

    - role: gnome
      tags:
        - user
        - desktop

    - role: bash
      tags:
        - user

    - role: go
      tags:
        - user

    - role: anyenv
      tags:
        - user
        - language

    - role: haskell-stack
      become: yes
      tags:
        - system
        - language
