---
- hosts: localhost
  connection: local

  roles:
    - role: base
      become: yes
      tags:
        - system

    - role: ansible
      become: yes
      tags:
        - system

    - role: oea
      become: yes
      tags:
        - system

    - role: gnome
      when: lookup('env','DESKTOP_SESSION') | regex_search('gnome')
      tags:
        - user
        - desktop

    - role: bash
      tags:
        - user

    - role: go
      tags:
        - user

    - role: anyenv
      tags:
        - user
        - language

    - role: haskell-stack
      become: yes
      tags:
        - system
        - language
