---
- hosts: local
  roles:
    - role: geerlingguy.ansible
      become: yes
      tags:
        - system

    - role: base
      tags:
        - system

    - role: wintus.oea
      become: yes
      tags:
        - system

    - role: wintus.gnome
      tags:
        - user
        - system
        - desktop

    - role: fcitx
      tags:
        - system

    - role: wintus.bash-fragments
      tags:
        - user

    - role: wintus.fish
      tags:
        - system
        - user

    - role: wintus.git
      tags:
        - system
        - user

    - role: go
      tags:
        - user

    - role: wintus.anyenv
      tags:
        - user
        - system
        - language

    - role: wintus.haskell-stack
      tags:
        - system
        - language

    - role: rust
      tags:
        - system
        - language

    - role: geerlingguy.nodejs
      become: true
      tags:
        - system
        - language

    - role: yarn
      tags:
        - system
        - language

    - role: wintus.spacemacs
      tags:
        - user
        - system
