---
- hosts: local dev
  roles:
    - role: ansible
      tags:
        - system

    - role: base
      tags:
        - system

    - role: oea
      become: yes
      tags:
        - system

    - role: gnome
      when: lookup('env','XDG_CURRENT_DESKTOP') | regex_search('GNOME')
      tags:
        - user
        - desktop

    - role: fcitx
      tags:
        - system

    - role: bash
      tags:
        - user

    - role: fish
      tags:
        - system
        - user

    - role: emacs
      tags:
        - user

    - role: git
      tags:
        - system
        - user

    - role: jetbrains
      tags:
        - system

    - role: go
      tags:
        - user

    - role: anyenv
      tags:
        - user
        - language

    - role: haskell-stack
      tags:
        - system
        - language

    - role: rust
      tags:
        - system
        - language

    - role: nodejs
      become: yes
      tags:
        - system
        - language

    - role: clamav
      become: yes
      tags:
        - system
