---
- hosts: local
  roles:
    - role: geerlingguy.ansible
      become: yes
      tags:
        - system

    - role: base
      tags:
        - system

    - role: wintus.gnome
      tags:
        - user
        - system
        - desktop

    - role: wintus.bash-fragments
      tags:
        - user

    - role: wintus.fish
      tags:
        - system
        - user

    - role: wintus.git
      tags:
        - system
        - user

    # TODO: use community role
    - role: wintus.go-tools
      tags:
        - user
        - system

    - role: wintus.rust-tools
      tags:
        - user
        - system
        - language

    - role: wintus.anyenv
      tags:
        - user
        - system
        - language

    - role: wintus.haskell-stack
      tags:
        - system
        - language

    - role: wintus.yarn
      tags:
        - system
        - language

    - role: wintus.spacemacs
      tags:
        - user
        - system
