---

- name: install toolbox
  block:
    - name: create temporary directory
      tempfile:
        state: directory
      register: tmpdir

    - name: set vars
      set_fact:
        tarball: "{{ tmpdir.path }}/jetbrains-toolbox-{{ jetbrains_toolbox_version }}.tar.gz"
        checksum: "{{ tarball }}.sha256"

    - name: download checksum of tarball
      get_url:
        url: "https://download.jetbrains.com/toolbox/jetbrains-toolbox-{{ jetbrains_toolbox_version }}.tar.gz.sha256"
        dest: "{{ checksum }}"

    - name: download tarball for toolbox
      get_url:
        url: "https://download-cf.jetbrains.com/toolbox/jetbrains-toolbox-{{ jetbrains_toolbox_version }}.tar.gz"
        dest: "{{ tarball }}"
        sha256sum: "{{ lookup('file', checksum) | regex_search(hex) }}"
      vars:
        hex: ([a-f\d]+)

    - name: unarchive binary
      unarchive:
        src: "{{ tarball }}"
        dest: /usr/local/bin/
        mode: a+x
        extra_opts: --strip-components=1 # tar
      become: yes
