---

- name: install toolbox
  unarchive:
    remote_src: yes
    src: "https://download-cf.jetbrains.com/toolbox/jetbrains-toolbox-{{ toolbox_version }}.tar.gz"
    dest: /usr/local/bin
    mode: a+x
    extra_opts: --strip-components=1 # tar
  become: yes
