---

- name: install Node.js LTS (8.x)
  when: ansible_pkg_mgr == "apt"
  become: yes
  vars:
    installer_path: /tmp/setup_node_src_v8.sh
  block:
    - name: add apt key of NodeSource
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

    - name: add apt sources list file for the NodeSource Node.js v8.x repo
      copy:
        src: nodesource.list
        dest: /etc/apt/sources.list.d/

    - name: install Node.js
      apt:
        name: nodejs
        update_cache: yes
        cache_valid_time: 3600

- name: install Yarn
  import_tasks: yarn.yml
