---

- name: install yarn by apt
  when: ansible_pkg_mgr == "apt"
  become: yes
  block:
    - name: add apt key of yarn
      apt_key:
        url: https://dl.yarnpkg.com/debian/pubkey.gpg

    - name: add package repository of yarn
      copy:
        src: yarn.list
        dest: /etc/apt/sources.list.d/

    - name: remove cmdtest for installation
      apt:
        name: cmdtest
        state: absent

    - name: install yarn
      apt:
        name: yarn
        update_cache: yes

- name: add path to yarn
  copy:
    src: yarn.sh
    dest: /etc/profile.d/
    mode: a+x

- name: check global installed packages
  shell: yarn global list
  register: yarn_g_ls
  changed_when: no

- name: install package globally by yarn
  shell: "yarn global add {{ item }}"
  with_items:
    - flow-typed
  changed_when: item not in yarn_g_ls.stdout
