---

- name: install yarn by apt
  when: ansible_pkg_mgr == "apt"
  become: yes
  block:
    - name: add apt key of yarn
      apt_key:
        url: "{{ yarn_debian_repo_gpg_key_url }}"

    - name: Install YARN APT repo
      apt_repository:
        repo: "deb {{ yarn_debian_repo_url }} stable main"
        filename: "yarn"
        update_cache: yes

    - name: remove cmdtest for installation
      apt:
        name: cmdtest
        state: absent

    - name: install yarn
      apt:
        name: yarn
        update_cache: yes
        cache_valid_time: 3600

- name: add path to yarn
  copy:
    src: yarn.sh
    dest: /etc/profile.d/
    mode: a+x
  become: yes

- name: check global installed packages
  shell: yarn global list
  register: yarn_g_ls
  changed_when: no

- name: install package globally by yarn for current user
  shell: "yarn global add {{ item }}"
  with_items:
    - n
  changed_when: item not in yarn_g_ls.stdout
