- name: install GNOME shell extension with chrome
  package:
    name: chrome-gnome-shell

- name: set home folder names in English
  shell: LC_ALL=C xdg-user-dirs-update
  changed_when: no

- name: set UI scale automatic
  dconf:
    key: /org/gnome/desktop/interface/scaling-factor
    value: 0

- name: disable super key to open activity
  dconf:
    key: "/org/gnome/mutter/overlay-key"
    value: "''"

- name: set Emacs keybinding
  dconf:
    key: /org/gnome/desktop/interface/gtk-key-theme
    value: "'Emacs'"

- name: fix workspace up/down keybindings
  block:
    - name: set keybindings to move workspace up
      dconf:
        key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-up
        value: "{{ keybindings | to_json }}"
      vars:
        keybindings: ['<Super>Page_Up', '<Super><Alt>Up']

    - name: set keybindings to move workspace down
      dconf:
        key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-down
        value: "{{ keybindings | to_json }}"
      vars:
        keybindings: ['<Super>Page_Down', '<Super><Alt>Down']
