- name: install GNOME shell extension with chrome
  package:
    name: chrome-gnome-shell

- name: set home folder names in English
  shell: LC_ALL=C xdg-user-dirs-update
  changed_when: no

- name: set UI scale automatic
  dconf:
    key: /org/gnome/desktop/interface/scaling-factor
    value: 0

- name: disable super key to open activity
  dconf:
    key: "/org/gnome/mutter/overlay-key"
    value: "''"
