- name: install package
  become: yes
  block:
    - name: install git
      package:
        name: git

    - name: install tig
      package:
        name: tig

- name: set global git configs
  git_config:
    scope: global
    name: "{{ item.section }}.{{ item.name }}"
    value: "{{ item.value }}"
  with_items: "{{ global_git_configs }}"

- name: set global git aliases
  git_config:
    scope: global
    name: "{{ item.section }}.{{ item.name }}"
    value: "{{ item.value }}"
  with_items: "{{ global_git_aliases }}"

- name: copy global git ignore
  copy:
    src: ignore
    dest: ~/.config/git/
