- name: install package
  become: yes
  block:
    - name: install git
      package:
        name: git

    - name: install tig
      package:
        name: tig

  rescue:
    - name: skip become
      debug:
        msg: skip install

- name: set global git configs
  git_config:
    scope: global
    name: "{{ item.section }}.{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - "{{ global_git_configs }}"
    - "{{ global_git_aliases }}"

- name: copy global git ignore
  copy:
    src: ignore
    dest: "{{ git_config_dir }}/"

# core.excludesfile が設定されたときのため
- name: set custom global git ignore
  file:
    state: link
    path: ~/.gitignore_global
    src: "{{ git_config_dir }}/ignore"
