- name: install package
  become: yes
  block:
    - name: install git
      package:
        name: git

    - name: install tig
      package:
        name: tig

- name: ensure dir
  file:
    path: "{{ git_config_dir }}/conf.d"
    state: directory

- name: copy config files
  copy:
    src: "{{ item }}"
    dest: "{{ git_config_dir }}/conf.d"
  with_items:
    - aliases.ini
    - credential.ini

- name: make config from fragments
  assemble:
    src: "{{ git_config_dir }}/conf.d"
    dest: "{{ git_config_dir }}/include.ini"

- name: include config files
  blockinfile:
    dest: "{{ git_config }}"
    block: "{{ lookup('file', 'include.ini') }}"
