# work-around: http://qiita.com/tbuchi888/items/c03e7cbce8608b1c55f1

- name: "install {{ lang.name }} {{ lang.version }}"
  shell: "{{ lang.env }} install {{ lang.version }}"
  register: install
  ignore_errors: yes
  failed_when: install.rc != 0 and not 'already exists' in install.stderr
  changed_when: not 'already exists' in install.stderr
