---

- name: install anyenv
  git:
    repo: https://github.com/riywo/anyenv
    dest: "{{ anyenv_root }}"

- name: enable anyenv
  block:
    - name: set anyenv in profine
      copy:
        src: anyenv.sh
        dest: "{{ bash_profile_dir }}"
        mode: a+x

- name: install anyenv plugins
  git:
    repo: "{{ item.repo }}"
    dest: "{{ anyenv_root }}/plugins/{{ item.name }}"
  with_items:
    - name: anyenv-update
      repo: https://github.com/znz/anyenv-update.git
    - name: anyenv-git
      repo: https://github.com/znz/anyenv-git.git

- name: initialize anyenv
  shell: |
    source {{ bash_profile_dir }}/anyenv.sh
    anyenv install --force-init
  failed_when: no
  changed_when: no

# *env

- name: install rbenv dependencies
  import_tasks: rbenv.yml

- name: install *envs with plugins
  include_tasks: install/env.yml
  loop_control:
    loop_var: env
  with_items:
    - name: pyenv
    - name: rbenv
      plugins:
        - name: rbenv-default-gems
          repo: https://github.com/sstephenson/rbenv-default-gems.git

- name: set plugins of rbenv
  block:
    - name: "get path to rbenv root"
      shell: |
        source {{ bash_profile_dir }}/anyenv.sh
        rbenv root
      args:
        executable: /bin/bash
      register: rbenv_root
      changed_when: no

    - name: set default gem list
      copy:
        src: rbenv/default-gems
        dest: "{{ rbenv_root.stdout }}/default-gems"

- name: install each languages by *envs
  include_tasks: install/lang.yml
  loop_control:
    loop_var: lang
  with_items:
    - name: ruby
      env: rbenv
      version: "{{ ruby_version }}"

    # install at last
    - name: python
      env: pyenv
      version: "{{ python_version }}"

    - name: python2
      env: pyenv
      version: "{{ python2_version }}"

- name: set Python versions
  shell: |
    source {{ bash_profile_dir }}/anyenv.sh
    pyenv global {{ python2_version }} {{ python_version }}
  args:
    executable: /bin/bash
  changed_when: no
