- name: install anyenv
  git:
    repo: https://github.com/riywo/anyenv
    dest: "{{ anyenv_root }}"

- name: set anyenv in profine
  copy:
    src: anyenv.sh
    dest: "{{ bash_profile_dir }}"
    mode: a+x
  notify: reload profile

- name: force reload profile
  shell: . {{ bash_profile_path }}
  changed_when: no

- name: check envs
  shell: anyenv version
  register: anyenv_version
  changed_when: no
  failed_when: no

- name: install anyenv plugins
  git:
    repo: "{{ item.repo }}"
    dest: "{{ anyenv_root }}/plugins/{{ item.name }}"
  with_items:
    - name: anyenv-update
      repo: https://github.com/znz/anyenv-update.git
    - name: anyenv-git
      repo: https://github.com/znz/anyenv-git.git

# *env

- name: install rbenv dependencies
  import_tasks: rbenv.yml

- name: install *envs
  shell: "anyenv install {{ item }} --skip-existing"
  changed_when: no
  with_items:
    - rbenv
    - pyenv

- name: install each languages by *envs
  include_tasks: install.yml
  vars:
    lang: "{{ item }}"
  with_items:
    - name: python
      env: pyenv
      version: "{{ python_version }}"

    - name: python 2
      env: pyenv
      version: "{{ python2_version }}"

    - name: ruby
      env: rbenv
      version: "{{ ruby_version }}"
