- name: install anyenv
  git:
    repo: https://github.com/riywo/anyenv
    dest: "{{ anyenv_root }}"

- name: set anyenv in profine
  copy:
    src: anyenv.sh
    dest: "{{ bash_profile_dir }}"
    mode: a+x
  notify: reload profile

- name: force reload profile
  shell: . {{ bash_profile_path }}
  changed_when: no

- name: check envs
  shell: anyenv version
  register: anyenv_version
  changed_when: no
  failed_when: no

- name: install anyenv plugins
  git:
    repo: "{{ item.repo }}"
    dest: "{{ anyenv_root }}/plugins/{{ item.name }}"
  with_items:
    - name: anyenv-update
      repo: https://github.com/znz/anyenv-update.git
    - name: anyenv-git
      repo: https://github.com/znz/anyenv-git.git

# *env

- name: install rbenv dependencies
  import_tasks: rbenv.yml

- name: install *envs with plugins
  include_tasks: install/env.yml
  loop_control:
    loop_var: env
  with_items:
    - name: pyenv
    - name: rbenv
      plugins:
        - name: rbenv-default-gems
          repo: https://github.com/sstephenson/rbenv-default-gems.git

- name: set plugins of rbenv
  block:
    - name: "get path to rbenv root"
      shell: "rbenv root"
      register: rbenv_root
      changed_when: no

    - name: set default gem list
      copy:
        src: rbenv/default-gems
        dest: "{{ rbenv_root.stdout }}/default-gems"

- name: install each languages by *envs
  include_tasks: install/lang.yml
  loop_control:
    loop_var: lang
  with_items:
    - name: python
      env: pyenv
      version: "{{ python_version }}"

    - name: python 2
      env: pyenv
      version: "{{ python2_version }}"

    - name: ruby
      env: rbenv
      version: "{{ ruby_version }}"

- name: set Python versions
  shell: "pyenv global {{ python2_version }} {{ python_version }}"
  changed_when: no
