---

# hub command

- name: check hub installed
  shell: which hub
  register: which_hub
  failed_when: no
  changed_when: which_hub.rc != 0

- name: install hub
  when: which_hub is changed
  block:
  - name: get hub
    shell: go get -u github.com/github/hub

  - name: install hub with man
    shell: make install prefix=/usr/local
    args:
      chdir: $GOPATH/src/github.com/github/hub
    become: yes

- name: set hub profile
  copy:
    src: hub.sh
    dest: "{{ bash_profile_dir }}"
    mode: a+x

# ghq command

- name: check ghq installed
  shell: which ghq
  register: which_ghq
  changed_when: which_ghq.rc != 0
  failed_when: no

- name: install ghq
  shell: go get github.com/motemen/ghq
  when: which_ghq.rc != 0
