# hub command

- name: check hub installed
  shell: bash -lc 'which hub'
  register: which_hub
  changed_when: which_hub.rc != 0

- name: install hub
  shell: bash -lc 'go get github.com/github/hub'
  when: which_hub.rc != 0

# ghq command

- name: check ghq installed
  shell: bash -lc 'which ghq'
  register: which_ghq
  changed_when: which_ghq.rc != 0

- name: install ghq
  shell: bash -lc 'go get github.com/motemen/ghq'
  when: which_ghq.rc != 0

# peco command

- name: check peco installed
  stat:
    path: "{{ peco_path }}"
  register: which_peco

- block:
  - name: download peco
    get_url:
      url: "https://github.com/peco/peco/releases/download/{{ peco_version }}/{{ peco_type }}.tar.gz"
      dest: /tmp

  - name: extract peco
    unarchive:
      src: "/tmp/{{ peco_type }}.tar.gz"
      dest: /tmp

  - name: install peco
    command: "mv /tmp/{{ peco_type }}/peco {{ peco_path }}"

  when: not which_peco.stat.exists
