# hub command

- name: check hub installed
  shell: which hub
  register: which_hub
  changed_when: which_hub.rc != 0

- name: install hub
  shell: go get github.com/github/hub
  when: which_hub.rc != 0

- name: set hub profile
  copy:
    src: hub.sh
    dest: "{{ bash_profile_dir }}"
    mode: a+x
  notify: reload profile

# ghq command

- name: check ghq installed
  shell: which ghq
  register: which_ghq
  changed_when: which_ghq.rc != 0

- name: install ghq
  shell: go get github.com/motemen/ghq
  when: which_ghq.rc != 0

- name: set ghq profile
  copy:
    src: ghq.sh
    dest: "{{ bash_profile_dir }}"
    mode: a+x
  notify: reload profile

# peco command

- name: check peco installed
  stat:
    path: "{{ peco_path }}"
  register: which_peco

- block:
  - name: download peco
    get_url:
      url: "https://github.com/peco/peco/releases/download/{{ peco_version }}/{{ peco_type }}.tar.gz"
      dest: /tmp

  - name: extract peco
    unarchive:
      src: "/tmp/{{ peco_type }}.tar.gz"
      dest: /tmp

  - name: install peco
    command: "mv /tmp/{{ peco_type }}/peco {{ peco_path }}"

  when: not which_peco.stat.exists
