- name: set $GOPATH in profile
  template:
    src: golang.sh
    dest: ~/.bash.d/
    mode: 0755

# hub command

- name: check hub installed
  shell: which hub
  register: which_hub
  changed_when: which_hub.rc != 0
  ignore_errors: yes

- block:

  - name: download hub binary
    unarchive:
      remote_src: yes
      src: "{{ hub_url }}"
      dest: /tmp

  - name: install hub binary
    copy:
      src: "/tmp/hub-linux-amd64-{{ hub_version }}"
      dest: /usr/local/bin
    become: yes

  when: which_hub.rc != 0

- name: set hub profile
  copy:
    src: hub.sh
    dest: "{{ bash_profile_dir }}"
    mode: a+x
  notify: reload profile

# ghq command

- name: check ghq installed
  shell: which ghq
  register: which_ghq
  changed_when: which_ghq.rc != 0
  ignore_errors: yes

- name: install ghq
  shell: go get github.com/motemen/ghq
  when: which_ghq.rc != 0

- name: set ghq profile
  copy:
    src: ghq.sh
    dest: "{{ bash_profile_dir }}"
    mode: a+x
  notify: reload profile

# peco command

- name: check peco installed
  command: which peco
  register: which_peco
  ignore_errors: yes

- block:

  - name: download peco
    unarchive:
      remote_src: yes
      src: "{{ peco_url }}"
      dest: /tmp

  - name: install peco
    become: yes
    copy:
      src: "/tmp/{{ peco_type }}/bin/peco"
      dest: /usr/local/bin

  when: which_peco.rc != 0
