go_path: .go

hub_version: 2.2.9
hub_url: "https://github.com/github/hub/releases/download/v{{ hub_version }}/hub-linux-amd64-{{ hub_version }}.tgz"

peco_version: v0.5.1
peco_type: peco_linux_amd64
peco_url: "https://github.com/peco/peco/releases/download/{{ peco_version }}/{{ peco_type }}.tar.gz"
