# work-around: http://qiita.com/tbuchi888/items/c03e7cbce8608b1c55f1

- name: "install {{ lang.name }} {{ lang.version }}"
  shell: "{{ lang.env }} install {{ lang.version }} --skip-existing"
  register: install
  changed_when: install.stdout != ''
