---

- when: ansible_pkg_mgr == "apt"
  block:
    - name: add apt-fast PPA
      apt_repository:
        repo: ppa:apt-fast/stable

    - name: install apt-fast
      apt:
        name: apt-fast
        update_cache: yes
