---

- name: install base packages by apt
  when: ansible_pkg_mgr == "apt"
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - name: build-essential
  become: yes
