---

- name: by apt
  when: ansible_pkg_mgr == "apt"
  block:
    - name: install base packages by apt
      apt:
        name: "{{ item.name }}"
        state: "{{ item.state | default('present') }}"
      with_items:
        - name: build-essential

- name: install base packages
  package:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - name: curl
    - name: neovim
    - name: vim-gnome
    - name: peco
    - name: silversearcher-ag

- import_tasks: chrome.yml
