---

- import_tasks: apt.yml

- import_tasks: apt-fast.yml

- name: install base packages
  become: yes
  package:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  loop:
    - name: git
    - name: curl
    - name: vim
    - name: silversearcher-ag
    - name: fonts-firacode

- import_tasks: chrome.yml
