---

- import_tasks: apt.yml
  when: ansible_pkg_mgr == "apt"

- name: install base packages
  package:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - name: curl
    - name: neovim
    - name: vim-gnome
    - name: peco
    - name: silversearcher-ag
    - name: fonts-firacode

- import_tasks: chrome.yml
- import_tasks: apt-fast.yml
